#!/usr/bin/env python3
"""
Fit JOREK ASCII profile files to the analytic tanh+polynomial formula
and output JOREK namelist parameters.

JOREK analytic formula for each profile f(psi_n):
    prof0 = (f0 - f1) * (1 + c1*psi_n + c2*psi_n^2 + c3*psi_n^3)
    atn   = 0.5 - 0.5 * tanh((psi_n - barrier) / sigma)
    f     = prof0 * atn + f1

where:  c1, c2, c3  = coef(1:3)
        sigma        = coef(4)
        barrier      = coef(5)

Usage:
    python fit_jorek_profiles.py [options] <profile_file>

Options:
    --density  FILE      Fit density profile
    --temp     FILE      Fit temperature profile
    --ffprime  FILE      Fit FF' profile
    --velocity FILE      Fit toroidal velocity/rotation profile
    --output   PREFIX    Output file prefix (default: fitted)
    --psi-axis VAL       psi_axis value (default: read from file or 0)
    --psi-bnd  VAL       psi_bnd value (default: read from file or 1)
    --no-barrier         Don't fit the tanh barrier (use flat atn=0.5)

The input file format is:  psi_n  value   (any delimiter, comments with #)
psi_n should be in [0, 1] normalized coordinates.
"""

import numpy as np
from scipy.optimize import curve_fit
import sys
import os


def profile_formula(psi_n, f0, f1, c1, c2, c3, sigma, barrier):
    """
    JOREK analytic profile formula.
    f(psi_n) = prof0 * atn + f1
    """
    prof0 = (f0 - f1) * (1.0 + c1 * psi_n + c2 * psi_n**2 + c3 * psi_n**3)
    psi_star = np.clip((psi_n - barrier) / sigma, -40, 40)
    atn = 0.5 - 0.5 * np.tanh(psi_star)
    return prof0 * atn + f1


def profile_formula_no_barrier(psi_n, f0, f1, c1, c2, c3):
    """Without tanh barrier: f(psi_n) = prof0 + f1"""
    prof0 = (f0 - f1) * (1.0 + c1 * psi_n + c2 * psi_n**2 + c3 * psi_n**3)
    return prof0 + f1


def read_profile(filename):
    """Read a two-column ASCII profile file (psi_n, value)."""
    psi_n, values = [], []
    with open(filename) as f:
        for line in f:
            line = line.split('#')[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2:
                try:
                    psi_n.append(float(parts[0]))
                    values.append(float(parts[1]))
                except ValueError:
                    continue
    return np.array(psi_n), np.array(values)


def init_guess(psi_n, values):
    """Generate initial guess for fitting parameters."""
    f0 = values[0]
    f1 = values[-1]
    if f0 < f1:
        f0, f1 = f1, f0  # assume core > edge
    c1, c2, c3 = 0.0, 0.0, 0.0
    sigma = 0.05
    barrier = 0.95  # pedestal location
    return f0, f1, c1, c2, c3, sigma, barrier


def fit_profile(psi_n, values, use_barrier=True):
    """Fit profile data to JOREK analytic formula."""
    init = init_guess(psi_n, values)

    if use_barrier:
        func = profile_formula
        # bounds: f0>0, f1>=0, sigma>0, barrier in [0,1]
        bounds = (
            [1e-10, 1e-10, -10, -10, -10, 1e-4, 0.5],
            [np.inf, np.inf, 10, 10, 10, 0.5, 1.0],
        )
        try:
            popt, _ = curve_fit(func, psi_n, values, p0=init,
                                bounds=bounds, maxfev=10000)
        except Exception:
            popt = init
    else:
        func = profile_formula_no_barrier
        bounds = (
            [1e-10, 1e-10, -10, -10, -10],
            [np.inf, np.inf, 10, 10, 10],
        )
        try:
            popt, _ = curve_fit(func, psi_n, values, p0=init[:5],
                                bounds=bounds, maxfev=10000)
        except Exception:
            popt = init[:5]
        # pad with default tanh params
        popt = list(popt) + [0.05, 0.95]

    return popt


def write_jorek_input(fits, output_prefix="fitted"):
    """Write fitted parameters as JOREK namelist entries."""
    lines = []
    lines.append("! --- Fitted JOREK analytic profile parameters ---")
    lines.append("!     Generated by fit_jorek_profiles.py")
    lines.append("")

    for name, fit in fits.items():
        f0, f1, c1, c2, c3, sigma, barrier = fit
        lines.append(f"! {name} profile")
        lines.append(f"  {name}_0    = {f0:.6e}")
        lines.append(f"  {name}_1    = {f1:.6e}")
        lines.append(f"  {name}_coef = {c1:.6e}, {c2:.6e}, {c3:.6e}, {sigma:.6e}, {barrier:.6e}")
        lines.append("")

    outfile = f"{output_prefix}_profiles.in"
    with open(outfile, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Fitted parameters written to: {outfile}")
    return outfile


def plot_fits(psi_n_dict, values_dict, fits_dict, output_prefix="fitted"):
    """Quick diagnostic plot of fits vs data."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("(matplotlib not available, skipping plot)")
        return

    fig, axes = plt.subplots(1, len(fits_dict), figsize=(5 * len(fits_dict), 4))
    if len(fits_dict) == 1:
        axes = [axes]

    for ax, (name, fit) in zip(axes, fits_dict.items()):
        psi = psi_n_dict[name]
        data = values_dict[name]
        psi_fine = np.linspace(0, 1, 500)

        if len(fit) == 7:
            f0, f1, c1, c2, c3, sigma, barrier = fit
            fitted = profile_formula(psi_fine, *fit)
        else:
            f0, f1, c1, c2, c3 = fit
            fitted = profile_formula_no_barrier(psi_fine, *fit)

        ax.plot(psi, data, 'o', ms=2, label='data')
        ax.plot(psi_fine, fitted, '-', label='fit')
        ax.set_xlabel(r'$\psi_N$')
        ax.set_title(name)
        ax.legend()

    fig.tight_layout()
    plotfile = f"{output_prefix}_fits.png"
    fig.savefig(plotfile, dpi=150)
    print(f"Diagnostic plot saved to: {plotfile}")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Fit JOREK profile files to analytic formula")
    parser.add_argument('--density', help='Density profile file')
    parser.add_argument('--temp', help='Temperature profile file')
    parser.add_argument('--ffprime', help="FF' profile file")
    parser.add_argument('--velocity', help='Velocity/rotation profile file')
    parser.add_argument('--rhon', help='Neutral density profile file')
    parser.add_argument('--Te', help='Electron temperature profile file')
    parser.add_argument('--Ti', help='Ion temperature profile file')
    parser.add_argument('--output', default='fitted', help='Output prefix')
    parser.add_argument('--no-barrier', action='store_true',
                        help='Do not fit tanh barrier')
    parser.add_argument('--no-plot', action='store_true',
                        help='Skip diagnostic plot')
    args = parser.parse_args()

    # Map CLI flags to JOREK parameter names
    param_map = {}
    if args.density:
        param_map['rho'] = args.density
    if args.temp:
        param_map['T'] = args.temp
    if args.Te:
        param_map['Te'] = args.Te
    if args.Ti:
        param_map['Ti'] = args.Ti
    if args.ffprime:
        param_map['FF'] = args.ffprime
        param_map['ffprime'] = args.ffprime
    if args.velocity:
        param_map['V'] = args.velocity
    if args.rhon:
        param_map['rhon'] = args.rhon

    if not param_map:
        print("ERROR: No profile files specified.")
        print("Use --density, --temp, --ffprime, --velocity, etc.")
        sys.exit(1)

    psi_n_dict = {}
    values_dict = {}
    fits_dict = {}

    use_barrier = not args.no_barrier

    for name, filename in param_map.items():
        psi_n, vals = read_profile(filename)
        print(f"Read {name} profile: {len(psi_n)} points from '{filename}'")
        psi_n_dict[name] = psi_n
        values_dict[name] = vals
        fit = fit_profile(psi_n, vals, use_barrier=use_barrier)
        fits_dict[name] = fit

        if use_barrier:
            f0, f1, c1, c2, c3, sigma, barrier = fit
            print(f"  {name}_0={f0:.4e}, {name}_1={f1:.4e}")
            print(f"  {name}_coef(1:3)=[{c1:.4e}, {c2:.4e}, {c3:.4e}]")
            print(f"  {name}_coef(4:5)=[sigma={sigma:.4e}, barrier={barrier:.4e}]")
        else:
            f0, f1, c1, c2, c3 = fit
            print(f"  {name}_0={f0:.4e}, {name}_1={f1:.4e}")
            print(f"  {name}_coef(1:3)=[{c1:.4e}, {c2:.4e}, {c3:.4e}]")

    write_jorek_input(fits_dict, args.output)

    if not args.no_plot:
        plot_fits(psi_n_dict, values_dict, fits_dict, args.output)


if __name__ == '__main__':
    main()
